name: 'my_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
test-paths: ["tests"]
docs-paths: ["docs"]
asset-paths: ["assets"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  supplychain_dbt_gold:
    staging:
      +schema: silver
      +materialized: view
    marts:
      +schema: gold
      +materialized: table